
services:
  postgres:
    image: postgres:15-alpine
    container_name: kanban-db
    environment:
      - POSTGRES_USER=kanbanuser
      - POSTGRES_PASSWORD=kanbanpass
      - POSTGRES_DB=kanban
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: kanban-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kanban
      - SPRING_DATASOURCE_USERNAME=kanbanuser
      - SPRING_DATASOURCE_PASSWORD=kanbanpass
      - APPLICATION_SECURITY_JWT_SECRET_KEY=645267556B58703273357638792F423F4528482B4D6251655468576D5A713474
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    container_name: kanban-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  postgres-data:
